### ISSUE TITLE
Create link from selection could work the other way around

### ISSUE THREAD

**Issue by NomarCub** [mii-key/obsidian-links#13]
When you have the URL on your clipboard and select something you can make a link with "Create link from selection".
I'd like it to work the other way around too: if you select an URL in text (needs to be detected in a simple way), and you have text on your clipboard, you can also make a link, like in https://github.com/denolehov/obsidian-url-into-selection.

PS:
Sorry for the issues all at once. I like your plugin, and I'd hope it could easily replace https://github.com/denolehov/obsidian-url-into-selection and https://github.com/zolrath/obsidian-auto-link-title for me and for others. These plugins have been around and useful for people for a while, but both are unmaintained.
You can look at their issues and pull requests to get some idea of what people want from a plugin like this. You could (and I think should) also advertise this plugin in those issues and PR threads, and threads about these old plugins in the Obsidian Forum and other places. You could probably get people contributing too, as they had done in the past.
If you point me to some places in code, I can try my hand at these features too. If you don't like these ideas or don't have the time for this I understand, but please elaborate how you stand on this.

**Comment by mii-key** [comment]
Thank you for your input and excellent ideas on the ways to improve and promote plugin. I find them very useful.

Please fill free to open issues on bugs and any missing features. The more the better ;)

BTW, thank you for the woderfull plugin<https://github.com/NomarCub/obsidian-open-vscode> - big helper!

**Comment by mii-key** [comment]
Plz check ['Set link text from clipboard'](https://github.com/mii-key/obsidian-links/blob/master/docs/insider/set-link-text-from-clipboard.md)  (enable in settings) in v. 1.8.3

**Comment by mii-key** [comment]
see v.1.12.1
