### ISSUE TITLE
Convert links in selections to Markdown links

### ISSUE THREAD

**Issue by libenling** [mii-key/obsidian-links#15]
Thank you for this great plugin! 

It would be great if there could be a possibility in the future to be able to select the entire text and apply the "Convert to Markdown link" to it instead of having to select each individual link.

**Comment by libenling** [comment]
Or a "Convert all wikilinks to Markdown links" function could be also great, because I'm looking for a easy way to convert wikilinks to Markdown links, so that my static webs generated by MkDocs works right.

**Comment by mii-key** [comment]
Thank you for the valuable suggestion.
plz check out the [Convert multiple links](https://github.com/mii-key/obsidian-links/blob/master/docs/insider/convert-multiple-links.md) feature.
The feature is WIP and will be extended later. 
Let me know if this works for you.
