### ISSUE TITLE
Feature Request: Option for Unlink to leave only header name behind

### ISSUE THREAD

**Issue by MalignantCarp** [mii-key/obsidian-links#18]
Right now, it seems whenever I unlink something where I link to a header, I get the entire link text left behind unless I also have display text.

For example, if I have a note called This Note and I am linking to its First Header, I would make a wikilink as [[This Note#First Header]]. When I run unlink on that, I get this left behind: This Note#First Header

If I have display text, so say [[This Note#First Header|It's a Header]], unlink leaves behind: It's a Header

Would it be possible to add an option to leave behind just the header name if there is no display text? In the example above, unlink would (ideally) leave behind just: First Header.

**Comment by mii-key** [comment]
Hi,
thank you for the valuable suggestion.

Plz check [Configure remove links from heading](https://github.com/mii-key/obsidian-links/blob/master/docs/insider/configure-remove-links-from-headings.md) feature.

I’m looking forward to receiving your feedback.

**Comment by MalignantCarp** [comment]
> Hi, thank you for the valuable suggestion.
> 
> Plz check [Configure remove links from heading](https://github.com/mii-key/obsidian-links/blob/master/docs/insider/configure-remove-links-from-headings.md) feature.
> 
> I’m looking forward to receiving your feedback.

That looks like it would do it, too.
