### ISSUE TITLE
Could it change all links in the entire library at once?

### ISSUE THREAD

**Issue by Immortal-Sty** [mii-key/obsidian-links#23]
I want to convert all Wiki links in the vault to Markdown links at once.

I have too many notes, and it will take a long time to transfer them one by one.

**Comment by mii-key** [comment]
Please, try [Obsidian Link Converter](https://github.com/ozntel/obsidian-link-converter).
Let me know how it works for you.

**Comment by Immortal-Sty** [comment]
It can't work well.

It converts `![[img.png|200]]` to `![](img.png)` instead of `![200](img.png)`.

**Comment by mii-key** [comment]
I see. I will implement this feature.

**Comment by Immortal-Sty** [comment]
Thanks.

**Comment by keiranlovett** [comment]
+1 to this, eagerly awaiting the feature

**Comment by mii-key** [comment]
Plz check v. 1.7.4
BACKUP YOUR DATA!

**Comment by Immortal-Sty** [comment]
It worked and no bugs or issues have been encountered so far.

**Comment by mii-key** [comment]
Great. Let me know, if you encounter any problems.
