### ISSUE TITLE
Ignore link formatting in codeblocks

### ISSUE THREAD

**Issue by keiranlovett** [mii-key/obsidian-links#24]
When using the plugin to convert links I occasionally get issues where code formatted with `[` and `]` in code blocks gets included.

For example

```diff
- [[ 1 < 2 ]] && echo "true"
+ [ 1 < 2 ](%201%20%3C%202%20) && echo "true"
```
and... 
```diff
- grep'^[[:blank:]]*[^[:blank:}#;}] filename.ext
+ grep'^[:blank:](:blank:)*[^[:blank:}#;}] filename.ext
```

**Comment by mii-key** [comment]
Thank you for the detailed bug report. I really appreciate your feedback!
Plz check v. [1.9.2](https://github.com/mii-key/obsidian-links/releases/tag/1.9.2).
Thanks again, and have a great day!
