### ISSUE TITLE
Feature Request: Copy paragraph block link

### ISSUE THREAD

**Issue by owbosh** [mii-key/obsidian-links#25]
What I'm humbly suggesting is implementation of this [simple plugin](https://github.com/mgmeyers/obsidian-copy-block-link), which is a very useful feature, but looks to be unmaintained. Creating/copying links from the right click context menu fits right at home with the Links plugin.

Thank you regardless for your work 👍

**Comment by mii-key** [comment]
Thank you for using the plugin and for your suggestion. I agree that the features of the mentioned plugin would be a great fit for this plugin. Could you please share features that you believe are missing from the [obsidian-copy-block-link](https://github.com/mgmeyers/obsidian-copy-block-link) that you would like to have?

**Comment by owbosh** [comment]
I'm not sure, I think the only 4 things it does is
- Copy link to block
- Copy link to block (embedded)
- Copy link to heading
- Copy link to heading (embedded)

Would adding anything else to this list make sense?

**Comment by CyrisZhang** [comment]
Implementation of this [simple plugin](https://github.com/mgmeyers/obsidian-copy-block-link) seems necessary to me , I'd like to say think you to add features as that plugin .What more , could you add another feature such as "copy link to block as wiki link"?

**Comment by notuntoward** [comment]
I've been looking exactly for something like:

- Copy link to block
- Copy link to heading

So it was great to see them in today's update.

I've also been hoping for one more thing:

- Copy link DWIM

which would copy a link to whatever the cursor is on: "Do What I Mean"

A couple editors I've used have these kinds of commands, and they're great because, first, you have to think less, and second, because you can map them to a single hotkey.

**Comment by mii-key** [comment]
I see your point. I can combine 'copy link to heading' and 'copy link to block' into the 'copy link' command.
Do you have anything else in mind?

**Comment by notuntoward** [comment]
Thanks!  Yes, I've got other ideas too. I'll make separate requests for them.

**Comment by mii-key** [comment]
plz check out v. 1.17.6. Enable 'copy link to element' in settings.

**Comment by notuntoward** [comment]
Thanks!  This works, and for me, is a big usability improvement. 
Even better would be (optional?) wikilinks (#33)
