### ISSUE TITLE
Markdown links should mention file extension

### ISSUE THREAD

**Issue by abrandst** [mii-key/obsidian-links#26]
I believe that markdown links to other markdown files should mention the file extension. After conversion e.g `[[../2022/Linux|Linux]]` becomes `[Linux](../2022/Linux)`. It reallly should be `[Linux](../2022/Linux.md)`, mostly because when copying the generated markdown files to gitlab, the links will be broken by the missing extension.

**Comment by abrandst** [comment]
I investigated a bit further: When I generate markdown links using the suggester in Obsidian by disabling "Use [[Wikilinks]]" and using the autosuggester, the link generated also includes the filename. This supports the idea that this is the correct behaviour.

**Comment by abrandst** [comment]
Wrote a fix. Not sure if it is good, please check.

https://github.com/mii-key/obsidian-links/pull/27

**Comment by mii-key** [comment]
Hello,

Thanks for using the plugin and for your feedback!

Plz check [Append .md extension](https://github.com/mii-key/obsidian-links/blob/master/docs/insider/convert-to-mdlink-append-mdextension.md).

Let me know if you encounter any problems.

Have a great day!

**Comment by abrandst** [comment]
Hi!

Looks great, works fine and I learned some new typescript tricks by looking through your commit.
Thank you for the great plugin, this is so useful!

**Comment by abrandst** [comment]
Local links do not work properly when the feature is enabled. 
Testcase:
1. Create a document like this (exclude triple backticks): 
```
# test
[[#test]]
```
2. Choose: Convert all links to markdown links

**Comment by mii-key** [comment]
Thank you for the detailed bug report!

Please check v. 1.10.12

Have a great day!
