### ISSUE TITLE
Ignore links in the frontmatter section

### ISSUE THREAD

**Issue by charles-halifax** [mii-key/obsidian-links#28]
Could you add an option to ignore links in the frontmatter section (it's also called "properties").
It's the section at the top of a document. Example:
```
---
title: Some title
author: John smith
---
```
So anything inside that delimiter of dashes is ignored.

Thank you.

**Comment by charles-halifax** [comment]
I'm sorry taking so long to reply.
In "`Convert wikilinks to markdown links`" command.
Thank you.

**Comment by mii-key** [comment]
Plz check v.1.13.2 (see [Skip Frontmatter](https://github.com/mii-key/obsidian-links/blob/master/docs/insider/skip-frontmatter.md))
