### ISSUE TITLE
Combine some commands into one

### ISSUE THREAD

**Issue by JINhuaqing** [mii-key/obsidian-links#30]
Could you combine some commands into one?

I use hotkey for this amazing Links plugin and it works great to improve my workflow. 
But for some commands, it may be more efficient to combine two commands into one to save the hotkey. 

For example, to **embed/unembed files**, it may be possible to simply combine two commands into a single embed/unembed one. 

Similar example include combine 
- **set link text and edit link text** into one.

**Comment by mii-key** [comment]
Thank you for the feedback. I'm glad that you find the plugin useful. 
Combining embed / unembed makes total sense.

**Comment by mii-key** [comment]
Plz check v. 1.15.0

**Comment by JINhuaqing** [comment]
> Plz check v. 1.15.0

Thanks, it works perfect now.
