### ISSUE TITLE
Feature Request: inhibit automatic link expansion

### ISSUE THREAD

**Issue by notuntoward** [mii-key/obsidian-links#31]
I navigate as much as possible by keyboard, but in obsidian, this is unusually messy, as obsidian expands a link any time you put a cursor on it.  This feature request would be to only expand links when asked to, and when asked, to make a popup or something like that.  

Besides improving keyboard navigation, it would improve the ergonomics of editing the link text and destination, and of clicking on links when you want to go there, not edit it.

There are more details on [my obsidian help feature request](https://forum.obsidian.md/t/how-to-inhibit-automatic-link-address-expansion/80141).  It's been up there for about a month with no takers, so I thought I'd shop it around here.

**Comment by mii-key** [comment]
I agree that link expansion is suboptimal. However, I do not see a straightforward way to implement this feature. In this specific case, the best option would be to move your request from Help to a Feature request.

**Comment by notuntoward** [comment]
Here's the Obsidian feature request, if anybody wants to vote for it:  [Inhibit automatic link address...](https://forum.obsidian.md/t/inhibit-automatic-link-address-expansion/85279?u=scotto)
