### ISSUE TITLE
Feature Request: Wikilink for Copy link to heading

### ISSUE THREAD

**Issue by notuntoward** [mii-key/obsidian-links#33]
Instead of markdown links, it seems it would be better if `Copy link to heading` made wikilinks.

A markdown link to a heading works fine as long as the linked-to heading's level stays the same.  But I'm constantly restructuring my note outlines, which breaks markdown heading links. 

However, wikilinks continue to work.  For example  `[[Test Note#Test Heading]]`  will match either `# Test Heading` or `### Test Heading`

One objection to heading wikilinks could be that they are ugly: [Test Note#Test Heading](bogusurl).  But this isn't a problem when using the [short links plugin](https://github.com/scottwillmoore/obsidian-short-links), which makes heading wikilinks appear identical to markdown links currently made by  `Copy link to heading`

**Comment by mii-key** [comment]
Please check out v. 1.17.7.
I assume you have `Use [[Wikilink]]` enabled in settings.
Have a nice day.

**Comment by notuntoward** [comment]
Yes, I did have  Use [[Wikilink]] set. But I just tried my test case again, and see that `copy link to element` makes a wikilink.  So it's working great.  Thanks for the useful features.
