### ISSUE TITLE
Hidden options

### ISSUE THREAD

**Issue by nefesh1-almagor1** [mii-key/obsidian-links#38]
Hello, the plugin has issues displaying all the link manipulation options, even though they are activated. Only two options are shown, as seen in the image. Also the keyboard shortcuts don't work either.

It is a very useful plugin for greater productivity, I hope the problem is solved!!

![Captura de pantalla 2024-08-14 184855](https://github.com/user-attachments/assets/4cd3642d-5ff0-4f2f-8663-97d205a61353)

**Comment by nefesh1-almagor1** [comment]
I found the problem and it is related to the use of parentheses () in the title of some notes that seems to conflict with the parentheses generated by a link, I removed the parentheses and the problem was solved.

**Comment by mii-key** [comment]
Hi, thank you for reporting this issue!

Could you please provide some typical examples where this error occurs, specifically including examples of the links that trigger the problem?

Thanks again!

**Comment by nefesh1-almagor1** [comment]
`[example1]([[note (1)#^abc]])`

**Comment by mii-key** [comment]
Please check out v. 1.17.15.

**Comment by nefesh1-almagor1** [comment]
Solved!!! Thank you very much
