### ISSUE TITLE
Question about deleted links and deleting the file

### ISSUE THREAD

**Issue by RealRavens** [mii-key/obsidian-links#39]
I was testing out the delete link feature since it'd really speed up my workflow. When I embedded a test note within another test note, I selected the delete option. It got rid of the link as it should, but didn't get rid of the file, neither was there a prompt to do so. So my assumption is that the link is referenced somewhere. But I used two new, blank notes not used anywhere else in the vault. Is there another way a note can be considered referenced? Otherwise, I really wish the delete link would also delete the file.

**Comment by mii-key** [comment]
Thanks a lot for spotting that bug! I'll have a fix out as soon as I can.

In the meantime, you might want to try setting Settings -> Files and links -> new link format to 'absolute path in vault' as a temporary workaround to help with the issue. 

If you notice anything else or have any more feedback, just let me know. Thanks again for your help!

**Comment by mii-key** [comment]
Plz check out v. 1.17.23.
I hope this solves the problem. Let me know if you need any further assistance.

**Comment by RealRavens** [comment]
Works like a charm 👍
