### ISSUE TITLE
Bug: obsidian crashes when  opening command pallete

### ISSUE THREAD

**Issue by machado-t** [mii-key/obsidian-links#45]
This plugin is causing obsidian to completely crash when opening the command pallete in android. Confirmed by disabling and enabling all plugins. I cannot give further details as I cannot open the console logs. Let me know if there's anything else I can do to further inform about this bug. Thanks for the plugin!

**Comment by mii-key** [comment]
Thank you for the bug report! I'm sorry to hear about the crash.
It would be very helpful if you could provide the content of the note that causes the crash. Additionally, please include the versions of Android, Obsidian, and the plugin you are using.
Have a nice day!

**Comment by machado-t** [comment]
I am sorry but I have disabled the plugin and I cannot try to replicate this bug anymore. I didn't consider that it could be note specific either. If I need to use it again in the future, I will give you better feedback. 
Thank you
