### ISSUE TITLE
Unlink all Links in selected Text

### ISSUE THREAD

**Issue by Flexihh** [mii-key/obsidian-links#8]
Thank you for this great plugin. It would be great if there could be a possibility in the future to be able to select the entire text and apply the "Unlink function" to it instead of having to select each individual link.

**Comment by mii-key** [comment]
Thank you! Glad you find the plugin usefull. The requested feature implemented in [v.1.1.0](https://github.com/mii-key/obsidian-links/releases/tag/1.1.0).
