### ISSUE TITLE
Update from 1.1.4 to 1.1.5 fails

### ISSUE THREAD

**Issue by pm64** [mii-key/obsidian-links#9]
After clicking "Update" on the Links entry in Obsidian's "Community plugins" pane, the error message "Failed to install plugin 'Links'" is displayed.

![image](https://github.com/mii-key/obsidian-links/assets/10715458/e0f372f1-ceac-4be7-9d18-90af22055e9e)

Let me know if there's any further diagnostic data I can provide to help resolve.

**Comment by mii-key** [comment]
thanks for the report. fixed.
